// setup_dpi.js
const fs = require('fs');
const path = require('path');

const projectFiles = {
  'package.json': JSON.stringify({
    name: "dpi-engine-mt",
    version: "1.0.0",
    description: "Multi-threaded Deep Packet Inspection engine in Node.js",
    main: "index.js",
    type: "module",
    scripts: {
      start: "node index.js input.pcap output.pcap"
    }
  }, null, 2),

  'types.js': [
    'export const AppType = {',
    '  UNKNOWN: "Unknown",',
    '  HTTPS: "HTTPS",',
    '  HTTP: "HTTP",',
    '  DNS: "DNS",',
    '  YOUTUBE: "YouTube",',
    '  FACEBOOK: "Facebook",',
    '  GOOGLE: "Google",',
    '  GITHUB: "GitHub"',
    '};',
    '',
    'export function hash5Tuple(tuple) {',
    '  const str = `${tuple.srcIp}:${tuple.srcPort}->${tuple.dstIp}:${tuple.dstPort}/${tuple.protocol}`;',
    '  let hash = 0x811c9dc5;',
    '  for (let i = 0; i < str.length; i++) {',
    '    hash ^= str.charCodeAt(i);',
    '    hash = Math.imul(hash, 0x01000193);',
    '  }',
    '  return (hash >>> 0);',
    '}',
    '',
    'export function classifyApp(sni) {',
    '  if (!sni) return AppType.HTTPS;',
    '  const s = sni.toLowerCase();',
    '  if (s.includes("youtube")) return AppType.YOUTUBE;',
    '  if (s.includes("facebook")) return AppType.FACEBOOK;',
    '  if (s.includes("google")) return AppType.GOOGLE;',
    '  if (s.includes("github")) return AppType.GITHUB;',
    '  return AppType.HTTPS;',
    '}'
  ].join('\n'),

  'sniExtractor.js': [
    'export function extractSNI(payload) {',
    '  try {',
    '    if (payload.length < 44 || payload[0] !== 0x16 || payload[5] !== 0x01) {',
    '      return null;',
    '    }',
    '',
    '    let offset = 43;',
    '    if (offset >= payload.length) return null;',
    '',
    '    const sessionIdLen = payload[offset];',
    '    offset += 1 + sessionIdLen;',
    '',
    '    if (offset + 2 > payload.length) return null;',
    '    const cipherSuitesLen = payload.readUInt16BE(offset);',
    '    offset += 2 + cipherSuitesLen;',
    '',
    '    if (offset + 1 > payload.length) return null;',
    '    const compMethodsLen = payload[offset];',
    '    offset += 1 + compMethodsLen;',
    '',
    '    if (offset + 2 > payload.length) return null;',
    '    const extensionsLen = payload.readUInt16BE(offset);',
    '    offset += 2;',
    '',
    '    const extensionsEnd = Math.min(offset + extensionsLen, payload.length);',
    '',
    '    while (offset + 4 <= extensionsEnd) {',
    '      const extType = payload.readUInt16BE(offset);',
    '      const extLen = payload.readUInt16BE(offset + 2);',
    '      offset += 4;',
    '',
    '      if (extType === 0x0000) {',
    '        if (offset + 5 <= extensionsEnd) {',
    '          const sniLen = payload.readUInt16BE(offset + 3);',
    '          const sniStart = offset + 5;',
    '          if (sniStart + sniLen <= extensionsEnd) {',
    '            return payload.toString("utf8", sniStart, sniStart + sniLen);',
    '          }',
    '        }',
    '      }',
    '      offset += extLen;',
    '    }',
    '  } catch {',
    '    return null;',
    '  }',
    '  return null;',
    '}'
  ].join('\n'),

  'packetParser.js': [
    'function ipToString(buf, offset) {',
    '  return `${buf[offset]}.${buf[offset + 1]}.${buf[offset + 2]}.${buf[offset + 3]}`;',
    '}',
    '',
    'export function parsePacket(rawBuf) {',
    '  if (rawBuf.length < 14) return null;',
    '',
    '  const etherType = rawBuf.readUInt16BE(12);',
    '  if (etherType !== 0x0800 || rawBuf.length < 34) return null;',
    '',
    '  const ipHeaderLen = (rawBuf[14] & 0x0f) * 4;',
    '  const protocol = rawBuf[23];',
    '  const srcIp = ipToString(rawBuf, 26);',
    '  const dstIp = ipToString(rawBuf, 30);',
    '',
    '  if (protocol === 6) {',
    '    const tcpOffset = 14 + ipHeaderLen;',
    '    if (rawBuf.length < tcpOffset + 20) return null;',
    '',
    '    const srcPort = rawBuf.readUInt16BE(tcpOffset);',
    '    const dstPort = rawBuf.readUInt16BE(tcpOffset + 2);',
    '    const tcpHeaderLen = ((rawBuf[tcpOffset + 12] >> 4) & 0x0f) * 4;',
    '    const payloadOffset = tcpOffset + tcpHeaderLen;',
    '',
    '    return {',
    '      tuple: { srcIp, dstIp, srcPort, dstPort, protocol: "TCP" },',
    '      payloadOffset: payloadOffset <= rawBuf.length ? payloadOffset : null',
    '    };',
    '  }',
    '',
    '  if (protocol === 17) {',
    '    const udpOffset = 14 + ipHeaderLen;',
    '    if (rawBuf.length < udpOffset + 8) return null;',
    '',
    '    const srcPort = rawBuf.readUInt16BE(udpOffset);',
    '    const dstPort = rawBuf.readUInt16BE(udpOffset + 2);',
    '',
    '    return {',
    '      tuple: { srcIp, dstIp, srcPort, dstPort, protocol: "UDP" },',
    '      payloadOffset: udpOffset + 8',
    '    };',
    '  }',
    '',
    '  return null;',
    '}'
  ].join('\n'),

  'worker.js': [
    'import { parentPort, workerData } from "worker_threads";',
    'import { extractSNI } from "./sniExtractor.js";',
    'import { classifyApp, AppType } from "./types.js";',
    '',
    'const { type, id, rules } = workerData;',
    '',
    'if (type === "LB") {',
    '  const fpPorts = [];',
    '  parentPort.on("message", (msg) => {',
    '    if (msg.cmd === "INIT_FP_PORT") {',
    '      fpPorts[msg.fpIndex] = msg.port;',
    '    } else if (msg.cmd === "PACKET") {',
    '      const fpIdx = msg.hash % fpPorts.length;',
    '      fpPorts[fpIdx].postMessage(msg, [msg.packetData.buffer]);',
    '    } else if (msg.cmd === "FLUSH") {',
    '      fpPorts.forEach((p) => p.postMessage({ cmd: "FLUSH" }));',
    '    }',
    '  });',
    '} else if (type === "FP") {',
    '  const flows = new Map();',
    '  let writerPort = null;',
    '  const stats = { processed: 0, dropped: 0, forwarded: 0, apps: {} };',
    '',
    '  parentPort.on("message", (msg) => {',
    '    if (msg.cmd === "INIT_WRITER_PORT") {',
    '      writerPort = msg.port;',
    '    } else if (msg.cmd === "CONNECT_LB") {',
    '      msg.port.on("message", (packetMsg) => {',
    '        if (packetMsg.cmd === "FLUSH") {',
    '          parentPort.postMessage({ cmd: "STATS", stats, id });',
    '          return;',
    '        }',
    '        processPacket(packetMsg);',
    '      });',
    '    }',
    '  });',
    '',
    '  function processPacket(msg) {',
    '    stats.processed++;',
    '    const { tuple, payloadOffset, packetData, headerBuf } = msg;',
    '    const flowKey = `${tuple.srcIp}:${tuple.srcPort}->${tuple.dstIp}:${tuple.dstPort}/${tuple.protocol}`;',
    '',
    '    let flow = flows.get(flowKey);',
    '    if (!flow) {',
    '      flow = { blocked: false, app: AppType.UNKNOWN, sni: null };',
    '      flows.set(flowKey, flow);',
    '    }',
    '',
    '    if (tuple.dstPort === 443 && payloadOffset && packetData.length > payloadOffset) {',
    '      const payload = Buffer.from(packetData.buffer, packetData.byteOffset + payloadOffset);',
    '      const sni = extractSNI(payload);',
    '      if (sni) {',
    '        flow.sni = sni;',
    '        flow.app = classifyApp(sni);',
    '        if (rules.blockedApps.includes(flow.app)) flow.blocked = true;',
    '        if (rules.blockedDomains.some((d) => sni.toLowerCase().includes(d.toLowerCase()))) {',
    '          flow.blocked = true;',
    '        }',
    '      }',
    '    }',
    '',
    '    if (rules.blockedIPs.includes(tuple.srcIp)) {',
    '      flow.blocked = true;',
    '    }',
    '',
    '    stats.apps[flow.app] = (stats.apps[flow.app] || 0) + 1;',
    '',
    '    if (flow.blocked) {',
    '      stats.dropped++;',
    '    } else {',
    '      stats.forwarded++;',
    '      writerPort.postMessage({ headerBuf, packetData }, [packetData.buffer]);',
    '    }',
    '  }',
    '}'
  ].join('\n'),

  'index.js': [
    'import fs from "fs";',
    'import { Worker, MessageChannel } from "worker_threads";',
    'import { parsePacket } from "./packetParser.js";',
    'import { hash5Tuple } from "./types.js";',
    '',
    'const inputFile = process.argv[2] || "test_dpi.pcap";',
    'const outputFile = process.argv[3] || "filtered.pcap";',
    'const NUM_LBS = 2;',
    'const NUM_FPS = 4;',
    'const rules = {',
    '  blockedApps: ["YouTube"],',
    '  blockedDomains: ["facebook"],',
    '  blockedIPs: ["192.168.1.50"]',
    '};',
    '',
    'if (!fs.existsSync(inputFile)) {',
    '  console.error(`Input file "${inputFile}" not found!`);',
    '  process.exit(1);',
    '}',
    '',
    'const inFd = fs.openSync(inputFile, "r");',
    'const outFd = fs.openSync(outputFile, "w");',
    '',
    'const globalHeader = Buffer.alloc(24);',
    'fs.readSync(inFd, globalHeader, 0, 24, null);',
    'fs.writeSync(outFd, globalHeader, 0, 24);',
    'const isLittleEndian = globalHeader.readUInt32LE(0) === 0xa1b2c3d4;',
    '',
    'const lbs = [];',
    'const fps = [];',
    '',
    'for (let i = 0; i < NUM_LBS; i++) {',
    '  lbs.push(new Worker("./worker.js", { workerData: { type: "LB", id: i, rules } }));',
    '}',
    'for (let i = 0; i < NUM_FPS; i++) {',
    '  fps.push(new Worker("./worker.js", { workerData: { type: "FP", id: i, rules } }));',
    '}',
    '',
    'lbs.forEach((lb) => {',
    '  fps.forEach((fp, fpIdx) => {',
    '    const { port1, port2 } = new MessageChannel();',
    '    lb.postMessage({ cmd: "INIT_FP_PORT", fpIndex: fpIdx, port: port1 }, [port1]);',
    '    fp.postMessage({ cmd: "CONNECT_LB", port: port2 }, [port2]);',
    '  });',
    '});',
    '',
    'fps.forEach((fp) => {',
    '  const { port1, port2 } = new MessageChannel();',
    '  fp.postMessage({ cmd: "INIT_WRITER_PORT", port: port1 }, [port1]);',
    '  port2.on("message", ({ headerBuf, packetData }) => {',
    '    fs.writeSync(outFd, Buffer.from(headerBuf));',
    '    fs.writeSync(outFd, Buffer.from(packetData));',
    '  });',
    '});',
    '',
    'let completedFPs = 0;',
    'const totalStats = { processed: 0, dropped: 0, forwarded: 0, apps: {} };',
    '',
    'fps.forEach((fp) => {',
    '  fp.on("message", (msg) => {',
    '    if (msg.cmd === "STATS") {',
    '      totalStats.processed += msg.stats.processed;',
    '      totalStats.dropped += msg.stats.dropped;',
    '      totalStats.forwarded += msg.stats.forwarded;',
    '      for (const [app, count] of Object.entries(msg.stats.apps)) {',
    '        totalStats.apps[app] = (totalStats.apps[app] || 0) + count;',
    '      }',
    '      completedFPs++;',
    '      if (completedFPs === NUM_FPS) {',
    '        finishExecution();',
    '      }',
    '    }',
    '  });',
    '});',
    '',
    'console.log(`[Reader] Dispatching packets from ${inputFile}...`);',
    'const pktHeaderBuf = Buffer.alloc(16);',
    '',
    'while (true) {',
    '  const bytesRead = fs.readSync(inFd, pktHeaderBuf, 0, 16, null);',
    '  if (bytesRead < 16) break;',
    '  const inclLen = isLittleEndian ? pktHeaderBuf.readUInt32LE(8) : pktHeaderBuf.readUInt32BE(8);',
    '  const packetData = Buffer.alloc(inclLen);',
    '  fs.readSync(inFd, packetData, 0, inclLen, null);',
    '',
    '  const parsed = parsePacket(packetData);',
    '  const headerCopy = Buffer.from(pktHeaderBuf);',
    '',
    '  if (parsed) {',
    '    const hash = hash5Tuple(parsed.tuple);',
    '    const lbIdx = hash % NUM_LBS;',
    '    lbs[lbIdx].postMessage({',
    '      cmd: "PACKET",',
    '      hash,',
    '      tuple: parsed.tuple,',
    '      payloadOffset: parsed.payloadOffset,',
    '      headerBuf: headerCopy,',
    '      packetData',
    '    }, [packetData.buffer]);',
    '  } else {',
    '    fs.writeSync(outFd, headerCopy);',
    '    fs.writeSync(outFd, packetData);',
    '    totalStats.forwarded++;',
    '  }',
    '}',
    '',
    'fs.closeSync(inFd);',
    'lbs.forEach((lb) => lb.postMessage({ cmd: "FLUSH" }));',
    '',
    'function finishExecution() {',
    '  fs.closeSync(outFd);',
    '  lbs.forEach((lb) => lb.terminate());',
    '  fps.forEach((fp) => fp.terminate());',
    '',
    '  console.log("\\n================ PROCESSING REPORT ================");',
    '  console.log(`Total Processed : ${totalStats.processed}`);',
    '  console.log(`Forwarded       : ${totalStats.forwarded}`);',
    '  console.log(`Dropped         : ${totalStats.dropped}`);',
    '  console.log("--- Application Breakdown ---");',
    '  for (const [app, count] of Object.entries(totalStats.apps)) {',
    '    console.log(`  ${app.padEnd(12)}: ${count} packets`);',
    '  }',
    '  console.log("===================================================\\n");',
    '  process.exit(0);',
    '}'
  ].join('\n')
};

for (const [filename, content] of Object.entries(projectFiles)) {
  fs.writeFileSync(path.resolve(filename), content, 'utf8');
  console.log('Created: ' + filename);
}

console.log('\nSetup complete! You can run the project using:\nnode index.js <input.pcap> <output.pcap>');